# ## installation of database in this case Nodejs
# dnf module list 
# dnf module disable nodejs -y
# dnf module enable nodejs:20 -y 
# dnf install nodejs -y
# cp back.service /etc/systemd/system/backend.service
# useradd expense
# mkdir /app 
# curl -o /tmp/backend.zip https://expense-web-app.s3.amazonaws.com/backend.zip 
# cd /app 
# unzip /tmp/backend.zip
# cd /app 
# npm install  
# chmod -R 775 /app
# chown -R expense:expense /app
# dnf install mysql-server -y
# mysql -h 3.92.176.39 -uroot -pExpenseApp@1 < /app/schema/backend.sql 
# systemctl daemon-reload
# systemctl enable backend 
# systemctl start backend

- name: disable a nodejs module.
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable a nodejs 20 version module.
  ansible.builtin.shell: dnf module enable nodejs:20 -y 

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: copy a file
  ansible.builtin.copy:
    src: back.service
    dest: /etc/systemd/system/backend.service

- name: Create user expense
  ansible.builtin.user:
    name: expense
    password: Expense@001
    create_home: yes # this will create the home directory

- name: Unarchive a file if it doesn't already exist
  ansible.builtin.unarchive:
    src: /https://expense-web-app.s3.amazonaws.com/backend.zip
    dest: /app
    creates: /app




